### ISSUE TITLE
Upstream go.zipexe dependency issue causes panic in Docker container

### ISSUE THREAD

**Issue by steddyman** [mroth/sseserver#17] opened 2023-08-02 17:36 UTC
I've spent quite a bit of time last month trying to containerize my Go project that is using SSE server.  Nothing I have tried works, leading me to believe SSE server must be partially implemented in C, and that C is throwing an exception up to Go (this is what the logs state).

I can build the image without errors, but can't get it to run within a container either on Docker or Kubernetes.

These are my current imports:
```
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"

	"github.com/mroth/sseserver"
)
```

This is my Dockerfile:
```
# syntax=docker/dockerfile:1
FROM golang:1.19

RUN apt-get update && apt-get install -y git

# Set destination for COPY
WORKDIR /app

# Copy the source code. Note the slash at the end, as explained in
COPY *.go ./

COPY go.sum go.mod ./

RUN go mod download

# Run
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /pusher-server .
# RUN go build -o /pusher-server

EXPOSE 8110

# Run
CMD ["/pusher-server"]
```

And this is the error I get running it in a Docker Container.  It works just fine with 'go run pusher-server.go':
```
 ⠿ Container pusher-server-pusher-server-1  Created                                                                                                                                              0.0s
Attaching to pusher-server-pusher-server-1
pusher-server-pusher-server-1  | panic: runtime error: invalid memory address or nil pointer dereference
pusher-server-pusher-server-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x64d2e6]
pusher-server-pusher-server-1  | 
pusher-server-pusher-server-1  | goroutine 1 [running]:
pusher-server-pusher-server-1  | debug/elf.(*Section).ReadAt(0xc000124000?, {0xc000132000?, 0x1c8?, 0x17?}, 0x40?)
pusher-server-pusher-server-1  |        <autogenerated>:1 +0x26
pusher-server-pusher-server-1  | archive/zip.readDirectoryEnd({0x76bde0, 0xc0000ca700}, 0x210)
pusher-server-pusher-server-1  |        /usr/local/go/src/archive/zip/reader.go:526 +0xf5
pusher-server-pusher-server-1  | archive/zip.(*Reader).init(0xc0000b6540, {0x76bde0?, 0xc0000ca700}, 0x210)
pusher-server-pusher-server-1  |        /usr/local/go/src/archive/zip/reader.go:97 +0x5c
pusher-server-pusher-server-1  | archive/zip.NewReader({0x76bde0, 0xc0000ca700}, 0x210)
pusher-server-pusher-server-1  |        /usr/local/go/src/archive/zip/reader.go:90 +0x5e
pusher-server-pusher-server-1  | github.com/daaku/go%2ezipexe.zipExeReaderElf({0x76c480?, 0xc000012048}, 0x752c87)
pusher-server-pusher-server-1  |        /go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:128 +0x8b
pusher-server-pusher-server-1  | github.com/daaku/go%2ezipexe.NewReader({0x76c480, 0xc000012048}, 0x0?)
pusher-server-pusher-server-1  |        /go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:48 +0x98
pusher-server-pusher-server-1  | github.com/daaku/go%2ezipexe.OpenCloser({0xc0000182e0?, 0xc000087be0?})
pusher-server-pusher-server-1  |        /go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:30 +0x57
pusher-server-pusher-server-1  | github.com/GeertJohan/go%2erice.init.0()
pusher-server-pusher-server-1  |        /go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/appended.go:42 +0x65
pusher-server-pusher-server-1 exited with code 2
```

**Comment by mroth** [comment] 2023-08-02 17:48
Interesting.  I recall I used to use this within a docker container, also built with `CGO_ENABLED=0`, so this should work. Looking at that panic, it appears to be caused by the `go.rice` module, which I used back in the day to embed the static HTML/CSS for the admin page in the binary. (`//go:embed` didn't exist yet, would almost certainly use it instead today).

It does look like there is an update to that module from this Dependabot PR #13.  I could try merging that and see if it helps. Note that I am not using this myself anymore (I no longer maintain emojitracker which is what I wrote it for back in the day) so I won't know if that works until you try it.  But game to try! Let me know.

Note that I started thinking about a few years (but didn't get around to) to [a total `v2` refactor](https://github.com/mroth/sseserver/tree/dev.v2) cleaning this library up and modernizing, (and potentially removing the admin page entirely anyhow).  I wasn't sure how many folks were actively using this project, so it wasn't a top priority compared to other projects.  I could probably do that in the next month or so if there is demand.

**Comment by mroth** [comment] 2023-08-02 17:55
Checking the dependencies, it looks like that is indeed the problem, see: https://github.com/GeertJohan/go.rice/commit/36628a95d1ee79e46bb7c47b0af540d69abee3f3

**Comment by mroth** [comment] 2023-08-02 18:00
@steddyman Can you update to the latest commit with that module bump merged and see if it addresses your issue?

`go get github.com/mroth/sseserver@e921f1f99c44b91db5cf9436a841a0a23b4b5890` should pin your project to it.

Please let me know, then if it works I'll bump the `v1` release version with that patch.

**Comment by steddyman** [comment] 2023-08-02 19:15
Thanks.  Certainly, I'll try that now.

**Comment by steddyman** [comment] 2023-08-02 19:33
Good news, that fixed it!  Many thanks.

From my debugging I had narrowed it down to that module, but noticed for some reason the zipexe module was not showing in the go.mod in the route of this repo, but is in mine as it seemed to be detecting and adding it when i did a 'go mod tidy' (even though I am not using the feature to bundle and stream an HTML file).

That's brilliant though, thanks for looking into it so quickly.  This was the last module of my app I needed to modularise.

**Comment by mroth** [comment] 2023-08-02 21:06
Fix released as https://github.com/mroth/sseserver/releases/tag/v1.1.2.

@steddyman you should be able to update to that version now instead of pinning to the commit SHA.

Thanks and let me know if you have any thoughts on a `v2`!

**Closed as completed by mroth** 2023-08-02 21:06 UTC
Labels: bug

**Comment by steddyman** [comment] 2023-08-02 21:31
Super, thanks.  Now that you mention it .... :)

Would this currently work from a client perspective if deployed behind a Kubernetes service active as a load balancer or using nodePorts?  So clients would all connect to the service, and it would direct the traffic across the different pods serving the backend?  I suspect maybe not

I could also front it with a single NGINX pod acting as a reverse proxy.

**Comment by steddyman** [comment] 2023-08-02 21:45
I can confirm it works with the new tag.  Many thanks.
